export const USA_States = [
  { label: "Alabama", value: "AL" },
  { label: "Alaska", value: "AK" },
  { label: "Arizona", value: "AZ" },
  { label: "Arkansas", value: "AR" },
  { label: "California", value: "CA" },
  { label: "Colorado", value: "CO" },
  { label: "Connecticut", value: "CT" },
  { label: "Delaware", value: "DE" },
  { label: "Florida", value: "FL" },
  { label: "Georgia", value: "GA" },
  { label: "Hawaii", value: "HI" },
  { label: "Idaho", value: "ID" },
  { label: "Illinois", value: "IL" },
  { label: "Indiana", value: "IN" },
  { label: "Iowa", value: "IA" },
  { label: "Kansas", value: "KS" },
  { label: "Kentucky", value: "KY" },
  { label: "Louisiana", value: "LA" },
  { label: "Maine", value: "ME" },
  { label: "Maryland", value: "MD" },
  { label: "Massachusetts", value: "MA" },
  { label: "Michigan", value: "MI" },
  { label: "Minnesota", value: "MN" },
  { label: "Mississippi", value: "MS" },
  { label: "Missouri", value: "MO" },
  { label: "Montana", value: "MT" },
  { label: "Nebraska", value: "NE" },
  { label: "Nevada", value: "NV" },
  { label: "New Hampshire", value: "NH" },
  { label: "New Jersey", value: "NJ" },
  { label: "New Mexico", value: "NM" },
  { label: "New York", value: "NY" },
  { label: "North Carolina", value: "NC" },
  { label: "North Dakota", value: "ND" },
  { label: "Ohio", value: "OH" },
  { label: "Oklahoma", value: "OK" },
  { label: "Oregon", value: "OR" },
  { label: "Pennsylvania", value: "PA" },
  { label: "Rhode Island", value: "RI" },
  { label: "South Carolina", value: "SC" },
  { label: "South Dakota", value: "SD" },
  { label: "Tennessee", value: "TN" },
  { label: "Texas", value: "TX" },
  { label: "Utah", value: "UT" },
  { label: "Vermont", value: "VT" },
  { label: "Virginia", value: "VA" },
  { label: "Washington", value: "WA" },
  { label: "West Virginia", value: "WV" },
  { label: "Wisconsin", value: "WI" },
  { label: "Wyoming", value: "WY" },
];

export const CANADA_States = [
  { label: "Alberta", value: "AB" },
  { label: "British Columbia", value: "BC" },
  { label: "Manitoba", value: "MB" },
  { label: "New Brunswick", value: "NB" },
  { label: "Newfoundland and Labrador", value: "NL" },
  { label: "Nova Scotia", value: "NS" },
  { label: "Ontario", value: "ON" },
  { label: "Prince Edward Island", value: "PE" },
  { label: "Quebec", value: "QC" },
  { label: "Saskatchewan", value: "SK" },
];

export const MEXICO_States = [
  { label: "Aguascalientes", value: "Ags." },
  { label: "Baja California", value: "B.C." },
  { label: "Baja California Sur", value: "B.C.S." },
  { label: "Campeche", value: "Camp." },
  { label: "Chiapas", value: "Chis." },
  { label: "Chihuahua", value: "Chih." },
  { label: "Ciudad de México", value: "CDMX" },
  { label: "Coahuila de Zaragoza", value: "Coah." },
  { label: "Colima", value: "Col." },
  { label: "Durango", value: "Dgo." },
  { label: "Guanajuato", value: "Gto." },
  { label: "Guerrero", value: "Gro." },
  { label: "Hidalgo", value: "Hgo." },
  { label: "Jalisco", value: "Jal." },
  { label: "México", value: "Méx." },
  { label: "Michoacán de Ocampo", value: "Mich." },
  { label: "Morelos", value: "Mor." },
  { label: "Nayarit", value: "Nay." },
  { label: "Nuevo León", value: "N.L." },
  { label: "Oaxaca", value: "Oax." },
  { label: "Puebla", value: "Pue." },
  { label: "Querétaro", value: "Qro." },
  { label: "Quintana Roo", value: "Q. Roo" },
  { label: "San Luis Potosí", value: "S.L.P." },
  { label: "Sinaloa", value: "Sin." },
  { label: "Sonora", value: "Son." },
  { label: "Tabasco", value: "Tab." },
  { label: "Tamaulipas", value: "Tamps." },
  { label: "Tlaxcala", value: "Tlax." },
  { label: "Veracruz de Ignacio de la Llave", value: "Ver." },
  { label: "Yucatán", value: "Yuc." },
  { label: "Zacatecas", value: "Zac." },
];

export const SPANISH_States = [
  { label: "Andalucía", value: "AN" },
  { label: "Aragón", value: "AR" },
  { label: "Asturias", value: "AS" },
  { label: "Islas Baleares", value: "IB" },
  { label: "Canarias", value: "CN" },
  { label: "Cantabria", value: "CB" },
  { label: "Castilla-La Mancha", value: "CM" },
  { label: "Castilla y León", value: "CL" },
  { label: "Cataluña", value: "CT" },
  { label: "Extremadura", value: "EX" },
  { label: "Galicia", value: "GA" },
  { label: "Madrid", value: "MD" },
  { label: "Murcia", value: "MC" },
  { label: "Navarra", value: "NC" },
  { label: "La Rioja", value: "RI" },
  { label: "País Vasco", value: "PV" },
  { label: "Valencia", value: "VC" },
  { label: "Ceuta", value: "CE" },
  { label: "Melilla", value: "ML" },
];

export const GERMANY_States = [
  { label: "Baden-Württemberg", value: "BW" },
  { label: "Bayern", value: "BY" },
  { label: "Berlin", value: "BE" },
  { label: "Brandenburg", value: "BB" },
  { label: "Bremen", value: "HB" },
  { label: "Hamburg", value: "HH" },
  { label: "Hessen", value: "HE" },
  { label: "Mecklenburg-Vorpommern", value: "MV" },
  { label: "Niedersachsen", value: "NI" },
  { label: "Nordrhein-Westfalen", value: "NW" },
  { label: "Rheinland-Pfalz", value: "RP" },
  { label: "Saarland", value: "SL" },
  { label: "Sachsen", value: "SN" },
  { label: "Sachsen-Anhalt", value: "ST" },
  { label: "Schleswig-Holstein", value: "SH" },
  { label: "Thüringen", value: "TH" },
];
